### ISSUE TITLE
settings wont open for me

### ISSUE THREAD

**Issue by mlgprobill** [EchoHackCmd/Swift-Client#1]
settings wont open for me so some of the mods dont work idk if u made it like that or if i just broke it

**Comment by EchoHackCmd** [comment]
You have to attach the game or settings won't enable.

**Comment by mlgprobill** [comment]
Thanks but that didn’t work I just copped and pasted it from a older
version and it works

**Comment by EchoHackCmd** [comment]
The issue was caused by "jesusval" having a value but not being registered (defined). It should work in the latest version, if the issue still persists then tell me.

**Comment by mlgprobill** [comment]
It works now thanks
